// Code generated by hertz generator.

package handler

import (
	"context"
	"io/ioutil"
	"net/http"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	c.JSON(consts.StatusOK, utils.H{
		"message": "pong",
	})
}

// download .
func DownloadPicture(ctx context.Context, c *app.RequestContext) {
	pictureUrl := c.Query("url")
	if pictureUrl == "" {
		c.JSON(consts.StatusOK, utils.H{
			"message": "参数错误",
		})
		return
	}

	resp, err := http.Get(pictureUrl)
	if err != nil {
		c.JSON(consts.StatusOK, utils.H{
			"message": "GET请求错误",
		})
		return
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)

	if resp.StatusCode != 200 {
		c.JSON(consts.StatusOK, utils.H{
			"message": "GET请求code错误",
		})
		return
	}

	c.JSON(consts.StatusOK, utils.H{
		"message": "成功",
		"data":    body,
	})
}
